authors:
  bryanpc01:
    name: Phil Bryan        # Author name
    description: A young man working to be a better man of God. # Author description
    avatar: https://avatars.githubusercontent.com/u/25752679?v=4&size=64         # Author avatar
    # slug: url           # Author profile slug
    # url: url            # Author website URL